name: visus_core_player

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  openidconnect: ^1.0.25
  flutter_svg: ^2.0.6
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  format: ^1.3.0
  dio: ^5.1.2
  validatorless: ^1.2.3
  flutter_overlay_loader: ^2.0.0
  loggy: ^2.0.2
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_typeahead: ^4.6.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  flutter_secure_storage: ^8.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
